stages:
  collect:
    cmd: python collect_data.py
    deps:
      - backend/raw_data.csv
    outs:
      - raw_data.csv
  preprocess:
    cmd: python preprocess_data.py
    deps:
      - raw_data.csv
    outs:
      - processed_data.csv
  train:
    cmd: python train_model.py
    deps:
      - processed_data.csv
    outs:
      - model.pkl
