stages:
  collect:
    cmd: python train_model.py collect
    deps:
      - backend/raw_data.csv
    outs:
      - raw_data.csv
  preprocess:
    cmd: python train_model.py preprocess
    deps:
      - raw_data.csv
    outs:
      - processed_data.csv
  train:
    cmd: python train_model.py train
    deps:
      - processed_data.csv
    outs:
      - model.pkl
